version: '3'


services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5432:5432"

  my-golang-app:
    container_name: my-golang-app
    build: ./

    depends_on:
      - postgres
    ports:
      - "8080:8080"


volumes:
  postgres-db:
    driver: local
